sudo: required
matrix:
  include:
    - language: ruby
      rvm:
        - 2.2
      before_install:
        - sudo apt-get update
        - sudo apt-get install chromium-chromedriver
      before_script:
        - "export PATH=$PATH:/usr/lib/chromium-browser/"
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start
    - language: java
      jdk:
        - oraclejdk8
      cache:
        directories:
          - $HOME/.m2
      install: true
      script: mvn clean install
      addons:
        ssh_known_hosts:
          - repo.maven.org